### PR TITLE
Add Xml Docs for Ignore the use of external resources #229

### PR DESCRIPTION
**Pull request by mb-jp**

### CODE REVIEW

**Comment by paulushub** [comment]
Thanks for the cooperation.

**Comment by mb-jp** [comment]
Thanks ! 

When do you think the next version of SharpVectors will be released ?

**Comment by paulushub** [comment]
> When do you think the next version of SharpVectors will be released ?

By Monday, we have enough feature set to up a version.

**Comment by paulushub** [comment]
@mb-jp Sorry for the delay, I am trying to improve the documentations a bit. It will surely be within this week.

**Comment by mb-jp** [comment]
@paulushub No problem, Take your time.

**Pull request merged**
