### PR TITLE
Make XmlReaderSettings globally configurable

### PR DESCRIPTION
**Pull request by MarvinPogoda**
This is a short term workaround to remove a possible attack surface for XXE-Attacks mentioned in #262 .

### CODE REVIEW

**Comment by paulushub** [comment]
It is a good idea, but only used in SharpVectorModel/DocumentStructure/SvgDocument.cs. So, it can safely live in that namespace, there is no need for a separate namespace. This could even be part of SvgDocument class, right?

**Comment by MarvinPogoda** [comment]
It is considerable to always deactivate dtdprocessing by default as suggested here:
Short version:
[](https://owasp.org/www-project-top-ten/2017/A4_2017-XML_External_Entities_(XXE))
More information:
[](https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html#net)

Package versions that use dtd-processing should be probably be marked as vulnerable.

**Comment by paulushub** [comment]
> Package versions that use dtd-processing should be probably be marked as vulnerable.

We can add a custom DTD resolver, and turn off entity resolutions to external documents.
SVG documents do use the entities.

**Comment by MarvinPogoda** [comment]
Is it possible to get a published nuget version, that includes this workaround?

**Comment by paulushub** [comment]
> Is it possible to get a published nuget version, that includes this workaround?

Let's make it Monday. Also hoping to find time and fix the issue this weekend.

**Pull request merged**
